### ISSUE TITLE
raster import error

### ISSUE THREAD

**Issue by yosukefk** [NCAR/finn-preprocessor#15]
Raster import fails.  You don't see the error at notebook, when raster got imported.  But symptom is that you dont get plot of raster from notebook.  

More direct alarm is in the terminal where notebook is started (docker exec), as seen below.  It says 'type "raster" does not exist".  PostGIS database does not how to deal with raster data, making it impossible to finn-preprocessor to work.

This error did not occur in Oct 2019, and I see now, Dec 2019.  So sometime during these two month period something got changed and raster capability of postgis is not enabled in our Dockerfile.   

<pre>
Creating output file that is 6000P x 6000L.
Processing ../proc_rst_modlct_2017/rsp/src.vrt [1/1] : 0...10...20...30...40...50...60...70...80...90...100 - done.
NOTICE:  schema "raster" already exists, skipping
NOTICE:  table "o_32_rst_modlct_2017" does not exist, skipping
NOTICE:  table "o_256_rst_modlct_2017" does not exist, skipping
NOTICE:  table "rst_modlct_2017" does not exist, skipping
Processing 1/1: ../proc_rst_modlct_2017/rsp/MCD12Q1.A2017001.r02c04.tif
ERROR:  type "raster" does not exist
LINE 1: ...."rst_modlct_2017" ("rid" serial PRIMARY KEY,"rast" raster);
                                                               ^
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
</pre>

**Comment by yosukefk** [comment]
@mbjoseph, do you remember seeing this when you wrote Docker file?  Seems like kartoza/postgis is not enabled for raster dataset, and we may have to do something in Docker, and the way that works may have changed, i am suspecting.

**Comment by mbjoseph** [comment]
Hi @yosukefk - no I don't remember that error, but it has been quite a while since I put the Dockerfile together. 

I don't know much about postgis, but I would guess that if you can reproduce the issue using the kartoza/postgis:11.0-2.5 image using a minimal example, then you might be able to get some help by opening an issue on the GitHub repo for the Docker image (https://github.com/kartoza/docker-postgis).

**Comment by yosukefk** [comment]
https://github.com/kartoza/docker-postgis/issues/172 I am thinking that this is at least one of cause of error.  Version of postgresql and postgis is drifting.  I try find work around.  I am thinking that it would make more sense to compile postgresql/postgis on my own...   That what i was doing on Linux shared cluster before we move this to docker, because there were a certain compile time option i neeed. 

I thought about moving to PostGIS 3.0 (with kartoza/postgis:12.0), but there seems to be issue of migrating PostgreSQL, similar to this one  https://github.com/OSGeo/gdal/issues/1692 .  One feature in postgreql got deprecated/removed, and causing trouble.  They fix the problem, but because of dependency to some other library ("basemap" for matplotlib doesnt seem to very active, for example), i can get this fixed easily in my setting.  GDAL/GEOS library is always a headache to get it work straight, in any environment.

Once I got this fixed, can we somehow post the docker image somehow?  User is going to "docker pull finn-preprocessor" and they don't have to build it on their own.  Would that stabilizes what's in the image?

**Comment by yosukefk** [comment]
#16 

If this backfires, remove two commands from Dockerfile that i am adding here.
