### ISSUE TITLE
freeze the image for distribution

### ISSUE THREAD

**Issue by yosukefk** [NCAR/finn-preprocessor#18]
#15 was caused by change in kartoza/postgis:11.0-2.5 .  main issue was that compile time support for raster got turned off in later version.  postgis version got changed but that was not a big issue for this project, turned out.  Still, it took me a day to sort out cause of problem and come up with solution.

I didn't find the problem until my colleague try to use this tool from scratch.  My local docker image was working fine.  I guess because i built it when kartoza/postgis had compile time support (in October 2019).  When i tried to build last week (December 2019), it pulled new version of kartoza/postgis, which was not compatible with how our Dockerfile are written, causing problem.

So I want to somehow freeze a working version of image, and make it one option to use for users.  I thought I can specify version of docker image, apt/conda packages to use, instead of just grab whatever.  But that approach wouldn't avoid the problem I saw in #15.  Another approach would be to use Docker-hub and allow user to docker pull.  Is it something easy to set up?  I also found https://stackoverflow.com/questions/24482822/how-to-share-my-docker-image-without-using-the-docker-hub this article too, if docker-hub is not the one we want.

**Comment by yosukefk** [comment]
@mbjoseph, appreciate your thoughts

**Comment by mbjoseph** [comment]
Docker Hub is a good option @yosukefk. You can set up an automated build that will allow users to use `docker pull` without needing to build the image themselves: https://docs.docker.com/docker-hub/builds/

**Comment by yosukefk** [comment]
https://hub.docker.com/r/yosukesabai/finn-preprocessor
Made this to get started but needs some brushing up:
- ideally it is hosted by ncar.  but ncar doesn't seem to have account for docker hub.  Should i prepare ncar-finn or something?  When i try they ask organization name, address etc, and i am not affiliated with ncar.
- i couldn't figure out how to pull from ncar git hub.  Maybe i just have to point somewhere?  I created dockerhub account long time ago, i don't remember what i did.  Anyway, so i made fork to my personal github account and then dockerhub pulls from there.  should be direct way to pull from ncar's repository
- Should it build image periodically/automatically? l think i just made one manually.  I pulled it, and also git clone (i need both git and docker image to run tool), and seems to be working.  that is a good thing.

I have been spending way too much time on this project last couple of days, so i have to set this aside for a while.

**Comment by mbjoseph** [comment]
I agree that an NCAR organization on Docker Hub should be the owner of the automated build, so that it builds from the NCAR/finn-preprocessor GitHub repository. 

We should build and test the image periodically (weekly?). This can be done on Travis CI, once the current issues are fixed: https://docs.travis-ci.com/user/docker/

**Comment by yosukefk** [comment]
Interesting.  Can I set it up to build off from NCAR site , but as myself?  I will ask if NCAR has plan to have docker accont.   I found NCAR's project which use docker, wrf_docker project https://ral.ucar.edu/projects/ncar-docker-wrf https://github.com/NCAR/WRF_DOCKER but it doesn't seem very active in development...  It seems to have only github repository like this project do.

**Comment by yosukefk** [comment]
same issue as #26
