### ISSUE TITLE
It takes a few minutes from docker run to actually the database is ready to go

### ISSUE THREAD

**Issue by yosukefk** [NCAR/finn-preprocessor#20]
This started happening after https://github.com/kartoza/docker-postgis/issues/172 this merged to karotza/postgis .  I tested if this tool works after the update in kartoza/postgis:11.0-2.5.  Seems like

- it takes longer for database setting up to take, a few minutes instead of less than a min.  So if i smoothly go from `docker run` to `docker exec`, database is not read.
- I thought what i did in #15 backfired, so i remove the runtime raster thing.  It still have the same problem
- If I `docker stop` and `docker start`, i think it is still slow to startup, or it may never come back, although i am not sure yet
- all of this I am testing on Mac with bind mounting (i.e., mounting Mac's native filesystem) for database.

Detailed symptoms are:

i start `docker run` , and look at `docker logs` . I see that database initialization hangs at
```
creating configuration files ... ok
```
subsequent messages are follows, so it maybe this bootstrap script is taking long time.
```
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok
```

I then `docker stop` and `docker start`, see if this is the problem of only database creation.   I see several error messages like below
```
2019-12-23 16:30:37.688 UTC [42] postgres@postgres FATAL:  the database system is starting up
psql: error: could not connect to server: FATAL:  the database system is starting up
```
But soon database becomes ready.  So it may be OK, although i thought that this `docker start` also acting funky earlier, and i cannot reproduce it as shown here. 
```
2019-12-23 16:30:47.675 UTC [226] LOG:  database system is ready to accept connections
```

**Comment by yosukefk** [comment]
@mbjoseph, I have to at least create frozen layer #18 ,  or I am even thinking of starting from debian image to reduce number of moving parts.  What do you think about this?

**Comment by mbjoseph** [comment]
Docker Hub is a good idea either way.

If you have time to build your own container from a Debian base image, that might reduce image size, which is good. Otherwise, it's probably fine to use the current base image.

**Comment by yosukefk** [comment]
This could have been using bind mounting when I am running docker from Mac.  If I do volume mounting, it doesn't seem to be an issue.  So, instead of bind mounting like top one below, you may use the one at the bottom, volume mounting.  

bind mounting
```
mkdir $HOME/pg_data
docker run --name finn -v ${HOME}/pg_data:/usr/lib/postgresql ...
```
volume mount
```
docker volume create pg_data
docker run --name finn -v pg_data:/usr/lib/postgresql ...
```
This just decides where the database is housed, and I thought it is better to be explicitly where the database is, instead of hidden inside the virtual machine for docker stuff.  With first method, they stay in $HOME/pg_data, in second method it is somewhere hidden in Docker's config, which is whale icon somewhere to bring up Docker config.  For mac, it happened to be /Users/yosuke/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw , and on PC, it was C:\Users\Public\Documents\Hyper-V\Virtual hard disks\DockerDesktop.vhdx.  In each case it is a giant file and inside it somehow database is stored, if you use bottom method. 

Having said that, the symptom I see is, in the cell near the top, checking PostGIS, you sill see something like this , "Connection refused", or any other unpleasant messages.
![Screen Shot 2019-12-23 at 8 48 12 AM](https://user-images.githubusercontent.com/19510255/71370829-f889ec80-2563-11ea-974a-a9e0c8a2be91.png)

I hope that this happen only when you `docker run` and then immediately go `docker exec` and start running code.  If you see that you wait for 5 min or so for database to initialize and start with the same cell (press `run` again).  You should see response like below, telling version of database.

![Screen Shot 2019-12-23 at 8 50 44 AM](https://user-images.githubusercontent.com/19510255/71370930-56b6cf80-2564-11ea-8da1-be6415f13ce3.png)
