### ISSUE TITLE
sudo required for linux?

### ISSUE THREAD

**Issue by yosukefk** [NCAR/finn-preprocessor#21]
I tested wit linux on my personal machine today, and seems like every docker command i have to use sudo.  Is this correct, @mbjoseph ?  Is there way to use this tool without admin previledge?  Just asking.

**Comment by mbjoseph** [comment]
@yosukefk Docker's post-installation steps have instructions on how to use Docker without sudo: https://docs.docker.com/install/linux/linux-postinstall/

**Comment by yosukefk** [comment]
Thanks, it is rather an involved process...  I go with sudo approach for this round of task.  But thanks, good to know that there is a way around.
