### ISSUE TITLE
create static docker image

### ISSUE THREAD

**Issue by yosukefk** [NCAR/finn-preprocessor#26]
@mbjoseph , 

Is there any way to create an image and hold onto it?  The image stopped working, and took me almost a day to find out what went wrong...

https://github.com/NCAR/finn-preprocessor/pull/25/

I know that i could have prevented this if i was verbose from the start.  But at the same time, I am wondering if i can distribute a image indepedenent of future changes that may occur in upstream images...

Thanks!

**Comment by mbjoseph** [comment]
@yosukefk yes!

I would recommend that you set up an automated build on Docker Hub if you haven't already. 

Then, you can pull a specific version by tag or by digest as described here: https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier

**Comment by yosukefk** [comment]
Thanks @mbjoseph .   I tried to set it up, but, thing is that the repository is owned by NCAR.  What do I need to do...?  

One thing i can think of is that i always mirror the repo to my personal account, and then set up docker hub to build off of my repository. Is that what you recommend too?

**Comment by mbjoseph** [comment]
That could work, but it would be cleaner to have just one GitHub repository. 

NCAR does have a DockerHub organization account (https://hub.docker.com/u/ncar) - is there someone who can add you to it, so that you can create a build for this repo?

**Comment by yosukefk** [comment]
Yeah, I should ask system guy how i can do that.  I should

**Comment by yosukefk** [comment]
@dattilo , do you know if you can do what Max @mbjoseph is suggesting ?   Basically i want to now how to let docker.com's ncar account to host the latest image from the github account (also by ncar, managed by me)

**Comment by dattilo** [comment]
I will inquire as to whether or not we can create "NCAR" docker hub accounts for non-NCAR/UCAR employees... If approved, you should receive an invite via email...

**Comment by yosukefk** [comment]
@dattilo, thank you for checking this in.  I got invitation to create docker id, with my university email.   I made one, and with the login , i see "ncar" as listed in my "organizations" list.  Let me try see if i can follow @mbjoseph 's instruction with this.

**Comment by yosukefk** [comment]
@mbjoseph , 

Not sure i should keep bothering you, but if there is something easy you can think of please let me know.  

I got docker ID, "yosukeut".   ncar is listed as my organization for docker account.  It is somewhat strange, however, that the organization has only one other user, and he is affiliated with ACOM (where Christine works for).  Anyways, i moved ahead.

I try follow this instruction https://docs.docker.com/docker-hub/builds/ .  I created repository at docker site as yosukeut/finn-preprocessor, and then go to "build" tab.  But for Organization part of Source Repository lists only "yosukefk" and "TACC", not "NCAR".   TACC is an UT organizational account where i am in a project.  yosukefk i believe that's whatever i have as myself.  Can you tell why i dont see NCAR/finn-processor from dockerhub?    

I checked github account's profile=>Organizations, and both NCAR and TACC are listed.  I should have been a NCAR participant since a year ago, before I started this TACC organization work...

If you have any advice please let me know.   I search docker forum and probably send email to docker site for help.

**Comment by yosukefk** [comment]
I thought re-establish link with github woudl help, like this said, https://hub.docker.com/support/doc/cant-access-new-github-organization-for-automated-builds 

I tried all steps twice (unlink from docker, revoke link from github, make new request from docker).  I still get only TACC, not the NCAR when i tried to setup auto build.  I thought it could be that below could be an issue.

> Also, if you're using a GitHub organization, your profile on your organization's people page (https://github.com/orgs/your-org/people) has to be set to public.

I am not listed under NCAR.  But so do I am not listed for TACC either.  So i am not sure if this is the source of error...   Do you have suggestion to what to try next?

https://github.com/orgs/TACC/people  This doesnt list me, but I can see TACC projects from docker hub
https://github.com/orgs/NCAR/people  This does not list me either, and i cannot see this NCAR listed when i try to set up automated build.  Only thing I can think of is that my email has utexas.edu which partly matches TACC's domain name (tacc.utexas.edu).  Do they care this...?  Am i getting access to TACC's project even though i am not listed as people, but because i ahve organizational mail address...?

**Comment by yosukefk** [comment]
Here is what I have now.

https://hub.docker.com/r/yosukeut/finn-preprocessor 
This is a repository i made.  In the github account, i created fork of NCAR version of finn-preprocessor, and docker hub is going to build it.

WIth this image, user follows Section 1/2/3 (prerequisite and `git clone`).  Then skip Section 4, Building Docker Image in the README.  and goes to Section 5.    Command to run differs only the last part, **yosukeut/finn-preprocessor**, instead of finn.  This will pull the built image from dockerhub, instead of building on local machine.  This should be a better way to let user run preprocessor, as the image is known to work, insteead of user grab source and build and it may not work as time passes.

```
# Create docker container and start
docker run --name finn -v ( (pwd | docker-path) + ':/home/finn') -v pg_data:/var/lib/postgresql -p 5432:5432 -p 8888:8888 -d -e EARTHDATAUSER=yourusername -e EARTHDATAPW=yourpassword yosukeut/finn-preprocessor
```

Instead of yosukeut/finn-preprocessor, it should be NCAR/finn-preprocessor when the dockerhub account are properly set up.

I am wondering i may have to find a volunteer from NCAR employee to mange the docker hub...?

**Comment by dattilo** [comment]
Are you asking me to become the "volunteer" for the managing the NCAR docker hub version? :-)

**Comment by yosukefk** [comment]
no...  i felt i needed this to be get done...  YOu gave me instruction and i have to refresh my memory and report you back what the issue was.  I probably need help from you then.  Although we have version of code without docker, i still think that docker is useful for portabliity.  Hope to get to dockerhub during this round of development.

**Comment by yosukefk** [comment]
@dattilo, do you know whom to contact for setting up a repository in NCAR docker hub?   One user had a hard time building image, and I thought it may make it easier for user to get preprocessor image

**Comment by dattilo** [comment]
Hi Yo,
   We have run out of "free" use on NCAR's dockerhub and our enterprise
group is still exploring the options. Github does have an image repository
itself which some groups have had good success with (and it was free the
las time I heard)...
Hope all is well,
Garth
--
NRIT Systems Administrator
***@***.***)
(Office: FL0-2110 Ph: 303-497-1471)
(Pronouns: he, him, his)
